FROM golang:1.25-alpine AS builder

WORKDIR /app

ENV CGO_ENABLED=0

COPY go.mod ./
RUN go mod download

COPY . .

RUN go build -o /out/api ./cmd/app

FROM alpine:3.20

WORKDIR /app

RUN adduser -D -u 10001 appuser

COPY --from=builder /out/api /usr/local/bin/api

EXPOSE 4000

USER appuser

ENTRYPOINT ["/usr/local/bin/api"]