FROM golang:1.25-alpine

WORKDIR /app

ENV GO111MODULE=on \
    CGO_ENABLED=0

RUN apk add --no-cache git

COPY go.mod go.sum ./
RUN go mod download

RUN go install github.com/air-verse/air@latest

COPY . .

EXPOSE 4000

CMD ["air", "-c", ".air.toml"]